Aconka/babot

babot.js
=> Bad fixes fixed hopefully

babot.js
many frogs can be made now with more holidays
=> Frog changes are now M O D U L A R

babot.js
=> create vote function

README.md, babot.js
=> when ist es? new command plus cool things on working 

babot.js
=> i hope this is the final one i need to do for this update

babot.js
=> bab  n ew comm and whtt daay fof weeeek and also may,be worrk with msuyitic boyut

babot.js
no bad update here, just fixes today
also baba can fix
=> discord done broke me plz work baba dont cry and the nw forgs will be thankfyl

babot.js
=> another obligatory holiday automation problem update

babot.js
=> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

babot.js
=> i seriously this hope is this the last one please for tonight baba please

babot.js
=> Holidays hotfix, thanks doscprd for breaking it again

babot.js
this is brougbth to you by NW FORGS
=> now instead ofk thej baba spaming the baba will only do single message for each commads

babot.js
=> multi-holification for the next event plus NW forg fixs

babot.js
sorting now haiky
and per person personalized perplexing personification of perchance haikus perposely perduced per message
no nw forogs
=> baba is now more haikurs and friday now but also m

babot.js, deployCommands.js
should i right a 10 page paper here?>
=> incompantnancy update

babot.js
=> cASE sENSITIVE

Commands/banHammer.js, Commands/friday.js, Commands/setVote.js, Commands/vibeTimeFlag.js, Commands/yugo.js, babot.js
10 page paper is behind you, watch out
=> vote <--> banhammer

Commands/coinflip.js, Commands/friday.js, Commands/haiku.js, Commands/hurricane.js, babot.js, commandFunctions.js, database.js, helperFunc.js, package.json, textCommands.js
something with hurricane update, adam is bullying me and more
=> baba moment with nw forge sponsorign the moment

Commands/hurricane.js, commandFunctions.js, database.js, helperFunc.js, textCommands.js
=> the baba easter egg update

commandFunctions.js, textCommands.js
!bsetgame watching you 👁️ 👄 👁️
=> hurricane hotfix

Commands/coinflip.js, babot.js, database.js, helperFunc.js, textExtra.js, voice.js
i cant spell becusse it is 3am somewhere
=> mikebug fixes and suck

Commands/cat.js, Commands/coinflip.js, Commands/frogDaysUntil.js, Commands/oven.js, Commands/uppus.js, babot.js, commandFunctions.js, dailycall.js, database.js, helperFunc.js, package.json, textCommands.js, textExtra.js
=> pizza time

Commands/delete.js, Commands/deleteContext.js, Commands/moveToContext.js, Commands/moveto.js, Commands/political.js, babot.js, contextMenu.js, dailycall.js, database.js, helperFunc.js, textCommands.js, textExtra.js
man fell into a quarrey and while there made a decision to spread the wisdom of the gliph to many who seek it
=> baba sure is pleased with your standings

Commands/friday.js, Commands/frog.js, babotdata.template.json, commandFunctions.js, dailycall.js, database.js, helperFunc.js, package.json, textCommands.js, textExtra.js
the update that updates the update
=> baba update update

Commands/friday.js, HelperFunctions/commandHelpers.js, HelperFunctions/genericHelpers.js, HelperFunctions/slashFridayHelpers.js, babot.js, commandFunctions.js, database.js, textCommands.js, textExtra.js
insert some deep inspirational quote here
=> no factory, no internet, no friday, no baba, what is life without all of them

Commands/friday.js, Commands/remind.js, HelperFunctions/basicHelpers.js, HelperFunctions/commandHelpers.js, HelperFunctions/slashFridayHelpers.js, commandFunctions.js, dailycall.js, database.js, textCommands.js, textExtra.js, voice.js
=> new year new baba

databaseandvoice.js
=> This one can be added sometime , just making it now so I don't forget

databaseandvoice.js
=> sorry for delay hank im drink right now

babot.js, databaseandvoice.js, textExtra.js
=> I lie in bed sick making this commit

HelperFunctions/basicHelpers.js, HelperFunctions/dbHelpers.js, HelperFunctions/slashFridayHelpers.js, commandFunctions.js, contextMenu.js, databaseandvoice.js, textExtra.js
please help they are discussing the political debate in voice 😭 🔫
=> baba pleasefishhaikufridaydbdown update

HelperFunctions/basicHelpers.js, HelperFunctions/slashFridayHelpers.js, textExtra.js
i think it was a fix for the fish
=> somethings changed?

HelperFunctions/commandHelpers.js, databaseandvoice.js
making it all promises means it will promise to work right?
that is how coding works
=> i swear this is the last hurricane fix

HelperFunctions/slashFridayHelpers.js
i made an oopsy woospy please hank fix bffore midnight so the db doesnt get cluttered
=> URGENT BABA FIX TO SAVE MANKIND

Commands/eve.js, Commands/friday.js, Commands/frogDayOfWeek.js, Commands/frogDaysUntil.js, Commands/frogWednesday.js, Commands/frogWhenIs.js, Commands/haiku.js, Commands/morshu.js, HelperFunctions/basicHelpers.js, HelperFunctions/commandHelpers.js, HelperFunctions/slashFridayHelpers.js, babot.js, commandFunctions.js, contextMenu.js, databaseVoiceController.js, databaseandvoice.js, testing.js, textCommands.js
she replace my cheeps until i reinstall windows
=> something something baba fixes and also refreshed /wednesday + 2 new commands because funny
